#!/usr/bin/env bash

#function exit_trap () {
#        exit $1
#}
#
#if [ -f /submission/dependencies ] ; then
#    cd /judge
#    awk -F ":::" -f dep.awk /submission/dependencies | xargs -r -L 1 sh -c 'python3 $0 $@ || exit 255' || exit_trap 7
#fi

